kind: "BuildConfig"
apiVersion: "v1"
metadata:
  name: springorchestrator
spec:
  source:
    git:
      ref: master
      uri: 'https://github.com/Trishna-Chakraborty/springorchestrator'
    sourceSecret:
      name: github-secret
    type: Git
  strategy:
    jenkinsPipelineStrategy:
      jenkinsfilePath: jenkins/JenkinsfileOrchestrator
    type: JenkinsPipeline